### ISSUE TITLE
Networking - Use an injected session when performing a network request.

### ISSUE THREAD

**Issue by Milos** [zuhlke/Support#21]
@mohsenr, looks like we forgot to use an injected `URLSessionProtocol` session here:

https://github.com/zuhlke/Support/blob/fafd24b659c891b5de76601fa4b0a039a4dd4663/Sources/Support/Networking/URLSessionHTTPClient.swift#L27

**Comment by mohsenr** [comment]
Good catch, thanks. This is a regression as part of the switch to async/await I believe.

It’s fixed in `3.0.1`.
